apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "profiling-demo.fullname" . }}
  labels:
    app: {{ include "profiling-demo.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "profiling-demo.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "profiling-demo.name" . }}
    spec:
      containers:
        - name: {{ include "profiling-demo.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "{{ .Values.env.SPRING_PROFILES_ACTIVE }}"
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: {{ .Values.resources.requests.memory }}
              cpu: {{ .Values.resources.requests.cpu }}
            limits:
              memory: {{ .Values.resources.limits.memory }}
              cpu: {{ .Values.resources.limits.cpu }}
